language: cpp
sudo: required

env:
  matrix:
    - NPGE_TARGET=linux NPGE_TESTDIR=npge-build-linux
    - NPGE_TARGET=windows MXE_TARGET=i686-w64-mingw32.static
    - NPGE_TARGET=windows MXE_TARGET=x86_64-w64-mingw32.static

install:
  - sudo apt-get update
  - ./linux/requirements.sh
  - ./${NPGE_TARGET}/requirements.sh
  - sudo ln -s /usr/bin/luajit-* /bin/luajit
  - sudo apt-get --yes install ncbi-blast+

script:
  - ./${NPGE_TARGET}/build.sh
  - if [ -n "$NPGE_TESTDIR" ]; then make test -C "$NPGE_TESTDIR"; fi

before_deploy:
  - ./${NPGE_TARGET}/deploy.sh
  - ls -l npge-build-*/npge_*
  - sha256sum npge-build-*/npge_*
  - awk 'sub("$", "\r")' README.md > README.txt

deploy:
  provider: releases
  api_key:
    secure: EsGeEACqIjkByNncKeRnrxfm0vNwaqwJmOaKXHC+nqJ3LOcQwP7Y5bbw8G8vSBwa2umTH9ZKt4HZV6HroYmD0kvoxjxlLQVcIfsjnSuOHp/oIMRJVXpaF1uejWUYHgZ7K5IlBQl1CWWnjH7NFypCvNt6lrl5oo64oCY3/tIeZmc=
  file:
      - "$(ls npge-build-linux/npge_*.tar.gz 2>/dev/null || echo README.txt)"
      - "$(ls npge-build-windows*/npge_*.exe 2>/dev/null || echo README.txt)"
      - "$(ls npge-build-windows*/npge_*.zip 2>/dev/null || echo README.txt)"
  skip_cleanup: true
  on:
    tags: true
