language: c

install:
  - sudo apt-get update
  - sudo ./linux/requirements.sh
  - sudo ln -s /usr/bin/luajit-* /bin/luajit
  - sudo apt-get install ncbi-blast+

script:
  - ./linux/build.sh
  - cd npge-build-linux
  - make test

before_deploy:
  - ./linux/package.sh
  - ls
  - export RELEASE_FILE=$(ls npge_*.tar.gz)

deploy:
  provider: releases
  api_key:
    secure: EsGeEACqIjkByNncKeRnrxfm0vNwaqwJmOaKXHC+nqJ3LOcQwP7Y5bbw8G8vSBwa2umTH9ZKt4HZV6HroYmD0kvoxjxlLQVcIfsjnSuOHp/oIMRJVXpaF1uejWUYHgZ7K5IlBQl1CWWnjH7NFypCvNt6lrl5oo64oCY3/tIeZmc=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
