#!/bin/bash

BRUCELLA_TEST_TABLE=$1
PROJECT_SOURCE_DIR=$2
PROJECT_BINARY_DIR=$3
CMAKE_CURRENT_SOURCE_DIR=$PROJECT_SOURCE_DIR/brucella
CMAKE_CURRENT_BINARY_DIR=$PROJECT_BINARY_DIR/brucella

make TARGET=$BRUCELLA_TEST_TABLE PROJECT_SOURCE_DIR=$PROJECT_SOURCE_DIR \
    PROJECT_BINARY_DIR=$PROJECT_BINARY_DIR \
    -f $CMAKE_CURRENT_SOURCE_DIR/brucella.make \
    -qp | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}' \
    > $CMAKE_CURRENT_BINARY_DIR/targets

